Use standard lib methods
exercism/crystal pull request #500
Opened 2023-09-29 13:52 UTC by ls1955

This commit:
* Refactor GeneratorHelp#to_capitalized
* Remove GeneratorHelp#to_snake
* Replace GeneratorHelp#to_snake with String#underscore

Associate Issue:
Closes #405

2023-09-29 15:00 UTC, ls1955 commented
Hmm... Can't figure out the error within space-age exercise.

2023-09-30 00:10 UTC, ls1955 commented
After taking a look around, It might be because we are dealing with int and float in space-age exercise?

```Crystal
num_one = 1000000000.to_s
num_two = 31.69.to_s

to_snake(num_one) # => "_1_0_0_0_0_0_0_0_0_0"
num_one.underscore # => "1000000000"
to_snake(num_two) # => "_3_1_._6_9"
num_two.underscore # => "31.69"
```

2023-09-30 12:38 UTC, ryanplusplus requested changes

2023-09-30 12:38 UTC, ryanplusplus commented on bin/generator_help.cr
We can remove `to_snake` now, right?

2023-09-30 12:39 UTC, ryanplusplus commented on bin/generator_help.cr
Never mind, I see it's still used in `space-age`. Let me see if I can find a way to use `String#underscore` in `space-age`.

2023-09-30 12:57 UTC, ryanplusplus approved these changes

2023-09-30 12:57 UTC, merged