Handle numerical issues complex_numbers_spec.cr
exercism/crystal pull request #528
Opened 2023-10-15 15:45 UTC by f-fr

The spec uses `eq` to test for equality of complex numbers. However, the real and imaginary parts are `Float64`, hence there might be numerical issues. Instead, the `be_close` expectation should be used.

Using `eq` would require the `Complex` class to be modified (e.g. by overloading `==` to be slightly imprecise). But this would somehow hard-code the precision of `Complex`, which would not be a good idea if `Complex` was a "production" implementation. Although it is only an exercise, it should not encourage "bad style" like this.

2023-10-15 15:51 UTC, ryanplusplus approved these changes

2023-10-15 16:17 UTC, ryanplusplus commented
The changes look good but they need to be done in the test template because the tests aren't generated instead of manually written.

2023-10-15 22:33 UTC, ryanplusplus requested changes
Make these changes in `exercises/practice/complex-numbers/.meta/test_template.ecr`

2023-10-16 09:08 UTC, f-fr commented
I could also modify the example solution and remove the `==` operator (it is not needed anymore).

2023-10-16 15:06 UTC, ryanplusplus commented
> I could also modify the example solution and remove the `==` operator (it is not needed anymore).

Yes please

2023-10-16 15:50 UTC, ryanplusplus approved these changes

2023-10-16 15:51 UTC, meatball133 approved these changes

2023-10-16 16:41 UTC, merged