[New Concept & Exercise]: Iteration
exercism/crystal pull request #627
Opened 2024-04-21 07:15 UTC by meatball133

2024-05-23 07:56 UTC, ErikSchierboom commented on exercises/concept/spellbound-steel/.docs/introduction.md
I feel like this might be introducing too much. It's not just iteration, it's also introducing:

- `present?`, `empty?`, `any?`, `all?`, `none?`, `one?`
- `count`
- `sort_by`

I would have expected this exercise to be about `each` and `times` and possibly `map` and `reduce`.

2024-06-01 12:23 UTC, ryanplusplus requested changes

2024-06-01 12:23 UTC, ryanplusplus commented on concepts/iteration/about.md
> +It also accepts an optional argument to specify the initial value of the sum.
```suggestion
The [`sum`][sum] method returns the sum of all elements in the collection.
It also accepts an optional block to transform the elements before summing them and an optional argument to specify the initial value of the sum.
```

2024-06-01 12:23 UTC, ryanplusplus commented on concepts/iteration/about.md
> +[`reduce`][reduce] or fold as it is known in other languages, is a method that with a combine method and an initial value, it will combine all the elements in the collection.
```suggestion
[`reduce`][reduce], or fold as it is known in other languages, is a method that with a combine method and an initial value combines all the elements in the collection.
```

2024-06-01 12:23 UTC, ryanplusplus commented on concepts/iteration/about.md
> +The `reduce` method has an accumulator that is passed to the block, the accumulator is the result of the previous iteration.
```suggestion
The `reduce` method has an accumulator that is passed to the block.
The accumulator is the result of the previous iteration.
```

2024-06-01 12:23 UTC, ryanplusplus commented on exercises/concept/spellbound-steel/.docs/hints.md
> +- There is a [built-in method][index] that can find the first element in the collection that meets the condition specified in the block, and return its index or `nil` if no element is found.
```suggestion
- There is a [built-in method][index] that can find the first element in the collection that meets the condition specified in the block and returns its index or `nil` if no element is found.
```

2024-06-01 12:23 UTC, ryanplusplus commented on exercises/concept/spellbound-steel/.docs/hints.md
> +- There is  a [built-in method][map] to transform all elements in the collection.
```suggestion
- There is a [built-in method][map] to transform all elements in the collection.
```

2024-06-01 12:23 UTC, ryanplusplus commented on exercises/concept/spellbound-steel/.docs/hints.md
> +- There is a [built-in method][capitalize] to capitalize a words for `String`.
```suggestion
- There is a [built-in method][capitalize] to capitalize all the words in a `String`.
```

2024-06-01 12:23 UTC, ryanplusplus commented on exercises/concept/spellbound-steel/.docs/instructions.md
> +## 1. Find card in the deck
```suggestion
## 1. Find a card in the deck
```

2024-06-01 12:23 UTC, ryanplusplus commented on exercises/concept/spellbound-steel/.docs/instructions.md
> +Therefore you want a method to tell you were you can find the first card in the deck of the kind you are looking for.
```suggestion
Therefore you want a method to tell you where you can find the first card in the deck of the kind you are looking for.
```

2024-06-01 12:23 UTC, ryanplusplus commented on exercises/concept/spellbound-steel/.docs/instructions.md
> +The power for all cards can been seen in the following table:
```suggestion
The power for all cards can be seen in the following table:
```

2024-06-01 12:23 UTC, ryanplusplus commented on exercises/concept/spellbound-steel/.docs/instructions.md
> +| Lightning Bolt | 35    |
```suggestion
| Lightning Bolt | 35     |
```

2024-06-01 12:23 UTC, ryanplusplus commented on exercises/concept/spellbound-steel/.docs/instructions.md
> +These cards is a hidden card that can only be decoded by the player who played it.
```suggestion
These are hidden cards that can only be decoded by the player who played them.
```

2024-06-01 12:23 UTC, ryanplusplus commented on exercises/concept/spellbound-steel/spec/spellbound_steel_spec.cr
> +    it "should return the first warriors index" do
```suggestion
    it "should return the index of the first Warrior" do
```

2024-06-01 12:23 UTC, ryanplusplus commented on exercises/concept/spellbound-steel/spec/spellbound_steel_spec.cr
> +    it "should return the first mages index" do
```suggestion
    it "should return the index of the first Mage" do
```

2024-06-01 12:23 UTC, ryanplusplus commented on exercises/concept/spellbound-steel/spec/spellbound_steel_spec.cr
> +    it "should work for different deck" do
```suggestion
    it "should work for a different deck" do
```

2024-06-01 12:23 UTC, ryanplusplus commented on exercises/concept/spellbound-steel/spec/spellbound_steel_spec.cr
> +    it "should capitalize the first letter of each word" do
```suggestion
    it "should capitalize the first letter of each word of a different list" do
```

2024-06-01 12:23 UTC, ryanplusplus commented on exercises/concept/spellbound-steel/spec/spellbound_steel_spec.cr
> +    it "should return 30 if the deck has one Warrior and one mage" do
```suggestion
    it "should return 30 if the deck has one Warrior and one Mage" do
```

2024-06-01 12:23 UTC, ryanplusplus commented on exercises/concept/spellbound-steel/spec/spellbound_steel_spec.cr
> +    it "should return 65 if the deck has a Rogue and Ice Storm " do
```suggestion
    it "should return 65 if the deck has a Rogue and an Ice Storm " do
```

2024-06-01 12:23 UTC, ryanplusplus commented on exercises/concept/spellbound-steel/spec/spellbound_steel_spec.cr
> +    it "should return warrior if the inut is wbalrrrlimoqr" do
```suggestion
    it "should return warrior if the input is wbalrrrlimoqr" do
```

2024-06-01 12:23 UTC, ryanplusplus commented on exercises/concept/spellbound-steel/spec/spellbound_steel_spec.cr
> +    it "should return mage if the inut is mlabgle" do
```suggestion
    it "should return mage if the input is mlabgle" do
```

2024-06-01 12:23 UTC, ryanplusplus commented on exercises/concept/spellbound-steel/spec/spellbound_steel_spec.cr
> +    it "should return rogue if the inut is rloguqgle" do
```suggestion
    it "should return rogue if the input is rloggquge" do
```

2024-06-01 12:23 UTC, ryanplusplus commented on exercises/concept/spellbound-steel/src/spellbound_steel.cr
> +
```suggestion
```

2024-07-17 22:13 UTC, ryanplusplus approved these changes

2024-07-17 22:13 UTC, merged